# FROM node:16.3.0-alpine
# WORKDIR /usr
# COPY . ./

# RUN npm install
# RUN npm run build

# EXPOSE 3002
# CMD ["node","dist/index.js"]




# Stage 1 - the build process
FROM node:16.3.0-alpine as build-deps
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

# Stage 2 - the production environment
FROM node:16-buster-slim
WORKDIR /usr/src/app
COPY --from=build-deps /usr/src/app/dist ./dist
COPY package*.json ./
RUN npm install --only=production

EXPOSE 3002
CMD ["node","dist/index.js"]